-- Migration 005: Businesses (core table)
CREATE TABLE IF NOT EXISTS businesses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(300) NOT NULL UNIQUE,
    description TEXT,
    short_description VARCHAR(500),
    address TEXT,
    city_id INT UNSIGNED NOT NULL,
    locality_id INT UNSIGNED DEFAULT NULL,
    state_id INT UNSIGNED NOT NULL,
    pin_code VARCHAR(10),
    phone VARCHAR(20),
    mobile VARCHAR(20),
    email VARCHAR(255),
    website VARCHAR(500),
    latitude DECIMAL(10,7) DEFAULT NULL,
    longitude DECIMAL(10,7) DEFAULT NULL,
    logo VARCHAR(500) DEFAULT NULL,
    cover_image VARCHAR(500) DEFAULT NULL,
    year_established YEAR DEFAULT NULL,
    owner_user_id INT UNSIGNED DEFAULT NULL,
    avg_rating DECIMAL(2,1) DEFAULT 0.0,
    total_reviews INT DEFAULT 0,
    is_verified TINYINT(1) DEFAULT 0,
    is_featured TINYINT(1) DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    status ENUM('pending','approved','rejected','suspended') DEFAULT 'pending',
    business_hours JSON DEFAULT NULL,
    social_links JSON DEFAULT NULL,
    meta_title VARCHAR(255) DEFAULT NULL,
    meta_description TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (city_id) REFERENCES cities(id),
    FOREIGN KEY (locality_id) REFERENCES localities(id) ON DELETE SET NULL,
    FOREIGN KEY (state_id) REFERENCES states(id),
    INDEX idx_biz_slug (slug),
    INDEX idx_biz_city (city_id),
    INDEX idx_biz_locality (locality_id),
    INDEX idx_biz_state (state_id),
    INDEX idx_biz_status (status, is_active),
    INDEX idx_biz_featured (is_featured, is_active),
    INDEX idx_biz_rating (avg_rating DESC),
    FULLTEXT INDEX idx_biz_search (name, description, short_description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
