-- Migration 018: Bookings - core marketplace transaction
CREATE TABLE IF NOT EXISTS bookings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    booking_number VARCHAR(20) NOT NULL UNIQUE,
    customer_id INT UNSIGNED NOT NULL,
    vendor_id INT UNSIGNED NOT NULL,
    business_id INT UNSIGNED NOT NULL,
    address_id INT UNSIGNED DEFAULT NULL,
    service_address TEXT DEFAULT NULL,
    service_latitude DECIMAL(10,7) DEFAULT NULL,
    service_longitude DECIMAL(10,7) DEFAULT NULL,
    scheduled_date DATE NOT NULL,
    scheduled_time TIME NOT NULL,
    status ENUM('pending','confirmed','assigned','in_progress','completed','cancelled','refunded') DEFAULT 'pending',
    subtotal DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    tax_amount DECIMAL(10,2) DEFAULT 0,
    total_amount DECIMAL(10,2) NOT NULL,
    commission_rate DECIMAL(5,2) DEFAULT 0,
    commission_amount DECIMAL(10,2) DEFAULT 0,
    vendor_payout_amount DECIMAL(10,2) DEFAULT 0,
    payment_status ENUM('pending','paid','partially_refunded','refunded','failed') DEFAULT 'pending',
    payment_method VARCHAR(50) DEFAULT NULL,
    cancellation_reason TEXT DEFAULT NULL,
    cancelled_by ENUM('customer','vendor','admin') DEFAULT NULL,
    customer_notes TEXT DEFAULT NULL,
    vendor_notes TEXT DEFAULT NULL,
    started_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    cancelled_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES users(id),
    FOREIGN KEY (vendor_id) REFERENCES users(id),
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (address_id) REFERENCES addresses(id) ON DELETE SET NULL,
    INDEX idx_book_customer (customer_id, status),
    INDEX idx_book_vendor (vendor_id, status),
    INDEX idx_book_status (status),
    INDEX idx_book_date (scheduled_date),
    INDEX idx_book_number (booking_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
